version: '3.8'

services:
  start-page:
    container_name: start-page
    image: excalith/start-page
    restart: unless-stopped
    ports:
      - 4000:3000
    volumes:
      - data:/app/data

volumes:
  data:
    name: excalith-start-page
